name: optimal_wrap_text
description: "A Flutter Text replacement that wraps short multi-line text over similarly sized lines for better visual balance."
version: 1.0.3
homepage: https://commingle.app
repository: https://github.com/chris-rutkowski/optimal_wrap_text

topics:
  - text
  - wrapping
  - ui
  - readability
  - responsive

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
